# Generated by Django 2.1.1 on 2018-09-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='device',
        ),
        migrations.AddField(
            model_name='employee',
            name='device_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
